services:
  minio:
    image: quay.io/minio/minio:RELEASE.2024-06-06T09-36-42Z
    volumes:
      - ./data:/data
    ports:
      - 9000:9000
      - 9001:9001
    restart: always
    environment:
      MINIO_ROOT_USER: 'minio_user'
      MINIO_ROOT_PASSWORD: 'minio_password'
      MINIO_ADDRESS: ':9000'
      MINIO_CONSOLE_ADDRESS: ':9001'
    command: minio server /data
